--liquibase formatted sql

--changeset ShilovaNatalia:tables

CREATE TABLE comments
(
    id         SERIAL PRIMARY KEY,
    ads_id     INTEGER,
    author_id  INTEGER,
    created_at VARCHAR(20),
    text       TEXT
);
CREATE TABLE users
(
    username varchar(50)  not null primary key,
    password varchar(120) not null,
    enabled  boolean      not null
);
CREATE TABLE profile_user
(
    user_profile_id SERIAL,
    email           VARCHAR(50),
    first_name      VARCHAR(50),
    last_name       VARCHAR(50),
    phone           VARCHAR(50),
    reg_date        VARCHAR(50),
    city            VARCHAR(50),
    avatar_id       INTEGER,
    CONSTRAINT pk_profile_user PRIMARY KEY (user_profile_id),
    FOREIGN KEY (email) REFERENCES users (username)
);
CREATE TABLE avatar
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_size  BIGINT                                  NOT NULL,
    media_type VARCHAR(255),
    data       BYTEA,
    CONSTRAINT pk_avatar PRIMARY KEY (id)
);
CREATE TABLE ads
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     INTEGER,
    title       VARCHAR(255),
    price       BIGINT                                 NOT NULL,
    description VARCHAR(255),
    CONSTRAINT pk_ads PRIMARY KEY (id)
);
CREATE TABLE image
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_size  BIGINT                                  NOT NULL,
    media_type VARCHAR(100),
    data       BYTEA,
    ads_id     INTEGER,
    generated_id_from_multipart_file                varchar(255),
    CONSTRAINT pk_image PRIMARY KEY (id)
);

CREATE TABLE authorities
(
    username  varchar(50) not null,
    authority varchar(50) not null,
    FOREIGN KEY (username) REFERENCES users (username)
);

--changeset ShilovaNatalia: keys
ALTER TABLE profile_user
    ADD CONSTRAINT FK_PROFILE_USER_ON_AVATAR FOREIGN KEY (avatar_id) REFERENCES avatar (id)
        on delete cascade on update cascade;

ALTER TABLE profile_user
    ADD CONSTRAINT unique_email unique (email);

ALTER TABLE ads
    ADD CONSTRAINT FK_ADS_ON_USER FOREIGN KEY (user_id) REFERENCES profile_user (user_profile_id)
        on delete cascade on update cascade;

ALTER TABLE  comments
    ADD CONSTRAINT fk_ads_user_profiles foreign key (author_id) REFERENCES profile_user (user_profile_id)
        on delete cascade on update cascade;

ALTER TABLE  comments
    ADD CONSTRAINT fk_ads foreign key (ads_id) REFERENCES ads (id)
        on delete cascade on update cascade;

ALTER TABLE image
    ADD CONSTRAINT FK_IMAGE_ON_ADS FOREIGN KEY (ads_id) REFERENCES ads (id)
        on delete cascade on update cascade;


